#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm nx run-many --target=lint --all;
pnpm nx run-many --target=build --all;
CI="true" pnpm nx run-many --target=test --all;
pnpm nx run-many --target=e2e --all;
